version: "3.9"

services:
  mongo:
    image: mongo:6.0
    container_name: genai_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: genai_backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/genai_db
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: genai_frontend
    restart: always
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend

volumes:
  mongo_data:
